name: sd
dependencies:
  - pytorch::pytorch
  - pytorch::torchvision
  - numpy
  - pillow
  - tqdm
  - pip:
    - pytorch-lightning>=1.7.7
    - einops
    - transformers
    - webdataset
    - open_clip_torch~=2.0
    - clip-anytorch~=2.5.0
    - -e git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k_diffusion
    - -e .
